### ISSUE TITLE
Disney+ - watch next episode automatically[FEATURE]

### ISSUE THREAD

**Issue by rekkersNZ** [Dreamlinerm/Netflix-Prime-Auto-Skip#103]
So when a episode finishes on disney+ - it wont autoplay the next episode..

**Comment by Dreamlinerm** [comment]
ok let me fix

**Comment by Dreamlinerm** [comment]
the skip still works for me, what browser are you using and which show is the problem @rekkersNZ  send me the link

**Comment by rekkersNZ** [comment]
Google Chrome - Version 124.0.6367.201 (Official Build) (64-bit) - Linux

Disney+ - Simpsons - plays full screen to the end, then minimizes to bottom right - does not auto-play next episode..

**Comment by Dreamlinerm** [comment]
I cannot quite replicate the bug, do you mind showing me in the discord server. https://discord.gg/5fBYathA7d

**Comment by Dreamlinerm** [comment]
fixed in 1.1.9, chrome version now online. need to find a way to check if its a different series now tho.
