### ISSUE TITLE
skip recurring intro songs

### ISSUE THREAD

**Issue by MurphyDoe0815** [Dreamlinerm/Netflix-Prime-Auto-Skip#105]
I'm excited about the feature of skipping the intros and opening sequences and intro songs, especially in series that are so annoyingly repetitive. Especially if you watch in a row. 
It works wonderfully on Netflix and I love the skipping!

Now I would like to have it everywhere from streamers. 
**WOW, Paramount+ and Disney** come to mind.
if this works i will only use the browser ;-)

Thank you very much

**Comment by Dreamlinerm** [comment]
@MurphyDoe0815 Disney is already supported. 
Paramount+ i can think about, but I would need login credentials for it to program it. 
The extension works on Firefox for android, which I use to chrome cast it on my TV btw.😉

**Comment by MurphyDoe0815** [comment]
Netflix kann man meiner Erfahrung nach auch nur über den Browser "teilen".
Sobald eine App ins Spiel kommt, blockiert er wegen der IP.
Hier vermute ich auch Android ?! - warum auch immer...
Das Problem habe ich im Browser nicht.

Du hattest übrigends Recht. 
Der Raspberry 4 war zu schwach auf der Brust.
Hier habe ich jetzt auf einen i3 mini PC gewechselt.
Den steuere ich mit einem mini Touchpad mit Mausfunktion.
Perfekt !!!

**Comment by Dreamlinerm** [comment]
nice, ich hab auchnochmal linux vs installiert da läufts ohne probleme.

**Comment by Dreamlinerm** [comment]
hast du erfahrung mit smarttube würde vltl jetzt probieren das zum laufen zu bringen auf meinem chromecast

**Comment by MurphyDoe0815** [comment]
Leider nein - sorry
Vielleicht solltest du dich mal mit den Jungs vom Projekt kurzschließen.
Die wissen eher auf was für einer Basis die Streams durchgeschleust werden können :-)

Wie machst du das mit den Accounts der verschiedenen Anbieter ? - Hier ist bei Smarttube ja nur 1 Account vorgesehen
Wechselt man innerhalb des Tubes, oder sollten mehrere Instanzen (Smarttubes mit verschiedene Namen) nebeneinander laufen können/müssen ?

**Comment by Dreamlinerm** [comment]
kann das von mir aus in verschiedene apks aufteilen mir egal, Seiten wechseln sollte man aber bestimmt auch hinbekommen

**Comment by Dreamlinerm** [comment]
@MurphyDoe0815 Ich habs übrigens hinbekommen. Meine Extension auf Android TV zu bekommen. 
Hab alles selber gemacht. Netflix geht da leider nicht, weil die genau wie auf Handy nicht erlauben leider. aber amazon prime und disney funktioniert normal.

**Comment by MurphyDoe0815** [comment]
Wenn es klappt - Glückwunsch !
So was wie smarttube, oder ein Extension Browser ?
Schon veröffentlicht ?

Bin übrigens immer noch begeistert von deiner Arbeit ;-)

**Comment by Dreamlinerm** [comment]
Naja glaube kaum das das in den android tv store kommt da gibts quasi nur so 60 apps, wenn kann man sowas nur wie smarttube sideloaden.
Öffne einfach mit webview die jeweilige webseite und injecte das script in die seite direkt. Hatte vorher nen fehler gemacht wo es nicht ging das ich dieses mal gefundne habe.
Muss relativ viel ädern damit die bedienung besser klappt, muss ma gucken wann ich da erste Version release.
Wenn würde ich denke ich seperate apks für amazon und disney etc. machen, weils halt einfacher ist.

**Comment by Dreamlinerm** [comment]
Ist aber vllt immernoch einfacher sein handy browser zu casten, je nach fernseher tbh.

**Comment by Dreamlinerm** [comment]
![Image](https://github.com/user-attachments/assets/a6ddf57e-debd-4721-9446-7a0a2fec95e9)

**Comment by Dreamlinerm** [comment]
![Image](https://github.com/user-attachments/assets/42268e19-8610-45af-bc35-1bb07cbe28df)

**Comment by MurphyDoe0815** [comment]
Du hast Recht. 
Mach eine App jeweils für Prime , Disney usw. 
Für mich bringt es nur als App in Verbindung für den FireTv Stick als Sideload.

Ansonsten nutze ich es mit Endeovor OS mit Brave und deiner Extension.
Wenn du es zu kompliziert machst, nutzt es wahrscheinlich keiner.
