### ISSUE TITLE
amazon prime intro überspringen [BUG]

### ISSUE THREAD

**Issue by Tantalus-X** [Dreamlinerm/Netflix-Prime-Auto-Skip#107]
Ich schaue zu Zeit Dr. House und King of Queens mir ist aufgefallen das Add-on die Intros nicht mehr überspringt, ich habe es schon resettet und komplett neu installiert

Mir ist aufgefallen, wenn das Add-on resettet geht es, solange bis man den Browser Neustart dann nicht mehr.
wäre schön wenn das gefixt wird

 - Exact URL: amazon.de
 - Country: deutschland
 - Browser: firefox: 127.0.2 64-bit
 - Addon-Version: 1.1.19

**Comment by Dreamlinerm** [comment]
aha ich gucke bei mir nach obs geht.
Falls es irgendwie an den Einstellungen liegt, kannst du auf die Einstellung Seite(Zahnrad) unter Backup und Reset gehen und die Einstellungen als eine Datei speichern und direkt angucken, ob da was falsch eingestellt ist, denke aber nicht das dass hier das Problem ist.

**Comment by Dreamlinerm** [comment]
also bei mir scheint dr. House zu gehen. Wenn das für dich ok ist, ist es wahrscheinlich am einfachsten, wenn du mir das Problem direkt über Discord zeigen könntest https://discord.gg/5fBYathA7d . Sonst kannst du mit F12 mir die console logs auf der webseite schicken wenns nicht funktioniert als ein screenshot oder text datei.

**Comment by Dreamlinerm** [comment]
welche folge genau ist bei der serie ein problem manchmal gibts da auch unterschiede

**Comment by Tantalus-X** [comment]
Also bei King of Queens müsstest du mal ab Staffel 2 schauen ich meine die haben da ersten ein Intro. bei dr House habe ich bis jetzt in allen Folgen dass das Intro nicht übersprungen wird

**Comment by Dreamlinerm** [comment]
> Also bei King of Queens müsstest du mal ab Staffel 2 schauen ich meine die haben da ersten ein Intro. bei dr House habe ich bis jetzt in allen Folgen dass das Intro nicht übersprungen wird

bei mir wirds übersprungen kannst du den log teilen oder mirs auf dem Discord server zeigen, ohne das kann ich glaube ich nicht viel anfangen. Da es ja beim Neuinstallieren aus irgendeinem Grund geht, denke ich mal das das Problem nicht auf der Seite ist.
