### ISSUE TITLE
[BUG] Disney+ crashing on landing page.

### ISSUE THREAD

**Issue by auqid** [Dreamlinerm/Netflix-Prime-Auto-Skip#109]
### Describe the bug
Disney+ crashing on landing page. stops responding. I get this error in console. Disney+ 

### To Reproduce
Just open the site and it crashes.

### Expected behavior
Not crash. 

### Background information:
 - Exact URL : https://www.hotstar.com/in/home
 - Country: India
 - Browser: Firefox
 - Addon-Version: 1.1.27
 - Save the console logs: 
 
 Streaming enhanced [skipper.js:107:13](moz-extension://acd969f0-fb66-4973-9b3f-ff227650044a/skipper.js)
version: 1.1.27 [skipper.js:108:13](moz-extension://acd969f0-fb66-4973-9b3f-ff227650044a/skipper.js)
Settings 
Object { Amazon: {…}, Netflix: {…}, Disney: {…}, Crunchyroll: {…}, HBO: {…}, Video: {…}, Statistics: {…}, General: {…} }
[skipper.js:109:13](moz-extension://acd969f0-fb66-4973-9b3f-ff227650044a/skipper.js)
Page Hotstar [skipper.js:114:33](moz-extension://acd969f0-fb66-4973-9b3f-ff227650044a/skipper.js)
20:46:44 started observing| PlayOnFullScreen [skipper.js:213:13](moz-extension://acd969f0-fb66-4973-9b3f-ff227650044a/skipper.js)
EmeEncryptionSchemePolyfill: Waiting to detect encryptionScheme support. [1106-9d970ac358bb1a6b.js:1:91624](https://www.hotstar.com/assets-x/web/_next/static/chunks/1106-9d970ac358bb1a6b.js)
McEncryptionSchemePolyfill: Waiting to detect encryptionScheme support. [1106-9d970ac358bb1a6b.js:1:91624](https://www.hotstar.com/assets-x/web/_next/static/chunks/1106-9d970ac358bb1a6b.js)
EmeEncryptionSchemePolyfill: Native encryptionScheme support found. 2 [1106-9d970ac358bb1a6b.js:1:91624](https://www.hotstar.com/assets-x/web/_next/static/chunks/1106-9d970ac358bb1a6b.js)
MODULE: Player Logger, CATEGORY: player-logger, MESSAGE: Supported Capabilities from PreCheck 
Object { video_codec: [], container: [], audio_channel: (1) […], encryption: (1) […], widevine_security_level: (1) […], widevine_hdcp_version: (1) […] }
[1106-9d970ac358bb1a6b.js:1:91624](https://www.hotstar.com/assets-x/web/_next/static/chunks/1106-9d970ac358bb1a6b.js)
MODULE: Player Logger, CATEGORY: player-logger, MESSAGE: Final Capabilities 
Object { clientCapabilities: {…}, drmParameters: {…} }
[1106-9d970ac358bb1a6b.js:1:91624](https://www.hotstar.com/assets-x/web/_next/static/chunks/1106-9d970ac358bb1a6b.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o478470.ingest.sentry.io/api/6223329/envelope/?sentry_key=d32fd9e4889d4669b234f07d232a697f&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.13.0. (Reason: CORS request did not succeed). Status code: (null).
2
WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. [175.277d69d35c4254ee.js:1:31483](https://www.hotstar.com/assets-x/web/_next/static/chunks/175.277d69d35c4254ee.js)
20:46:44 Recap skipped 
<div class="CIjKrcj-4Yl2QLlh0cHqd">
[skipper.js:213:13](moz-extension://acd969f0-fb66-4973-9b3f-ff227650044a/skipper.js)
20:46:44 Recap skipped 
<div class="CIjKrcj-4Yl2QLlh0cHqd">
[skipper.js:213:13](moz-extension://acd969f0-fb66-4973-9b3f-ff227650044a/skipper.js)
Error: Abort fetching component for route: "/[[...slug]]"
    NextJS 30

**Comment by Dreamlinerm** [comment]
So it is apparently skipping recap without a recap on the home screen, that's probably the error. I cannot go onto hot star since I can't make an account outside India. Would you be willing to help me over discord to fix it? https://discord.gg/5fBYathA7d

**Comment by Dreamlinerm** [comment]
a temporary fix for you is to disable the skip intro feature for disney

**Comment by Dreamlinerm** [comment]
> ### Describe the bug
> 
> Disney+ crashing on landing page. stops responding. I get this error in console. Disney+
> ### To Reproduce
> 
> Just open the site and it crashes.
> ### Expected behavior
> 
> Not crash.
> ### Background information:
> 
>     * Exact URL : https://www.hotstar.com/in/home
> 
>     * Country: India
> 
>     * Browser: Firefox
> 
>     * Addon-Version: 1.1.27
> 
>     * Save the console logs:
> 
> 
> Streaming enhanced skipper.js:107:13 version: 1.1.27 skipper.js:108:13 Settings Object { Amazon: {…}, Netflix: {…}, Disney: {…}, Crunchyroll: {…}, HBO: {…}, Video: {…}, Statistics: {…}, General: {…} } skipper.js:109:13 Page Hotstar skipper.js:114:33 20:46:44 started observing| PlayOnFullScreen skipper.js:213:13 EmeEncryptionSchemePolyfill: Waiting to detect encryptionScheme support. [1106-9d970ac358bb1a6b.js:1:91624](https://www.hotstar.com/assets-x/web/_next/static/chunks/1106-9d970ac358bb1a6b.js) McEncryptionSchemePolyfill: Waiting to detect encryptionScheme support. [1106-9d970ac358bb1a6b.js:1:91624](https://www.hotstar.com/assets-x/web/_next/static/chunks/1106-9d970ac358bb1a6b.js) EmeEncryptionSchemePolyfill: Native encryptionScheme support found. 2 [1106-9d970ac358bb1a6b.js:1:91624](https://www.hotstar.com/assets-x/web/_next/static/chunks/1106-9d970ac358bb1a6b.js) MODULE: Player Logger, CATEGORY: player-logger, MESSAGE: Supported Capabilities from PreCheck Object { video_codec: [], container: [], audio_channel: (1) […], encryption: (1) […], widevine_security_level: (1) […], widevine_hdcp_version: (1) […] } [1106-9d970ac358bb1a6b.js:1:91624](https://www.hotstar.com/assets-x/web/_next/static/chunks/1106-9d970ac358bb1a6b.js) MODULE: Player Logger, CATEGORY: player-logger, MESSAGE: Final Capabilities Object { clientCapabilities: {…}, drmParameters: {…} } [1106-9d970ac358bb1a6b.js:1:91624](https://www.hotstar.com/assets-x/web/_next/static/chunks/1106-9d970ac358bb1a6b.js) Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o478470.ingest.sentry.io/api/6223329/envelope/?sentry_key=d32fd9e4889d4669b234f07d232a697f&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.13.0. (Reason: CORS request did not succeed). Status code: (null). 2 WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. [175.277d69d35c4254ee.js:1:31483](https://www.hotstar.com/assets-x/web/_next/static/chunks/175.277d69d35c4254ee.js) 20:46:44 Recap skipped
> [skipper.js:213:13](moz-extension://acd969f0-fb66-4973-9b3f-ff227650044a/skipper.js) 20:46:44 Recap skipped
> [skipper.js:213:13](moz-extension://acd969f0-fb66-4973-9b3f-ff227650044a/skipper.js) Error: Abort fetching component for route: "/[[...slug]]" NextJS 30

The log was very helpful i know where the error is but, if the feature should not be disabled permanently, I need some help.
