### ISSUE TITLE
[FEATURE]Can the Improve video interface options be configured individually?

### ISSUE THREAD

**Issue by hokkaman** [Dreamlinerm/Netflix-Prime-Auto-Skip#114]
If Improve video interface is turned on, a subtitle appearance change and a speed slider will be added.

I would like to turn on the speed slider but turn off the subtitle appearance change.

Is it possible to have a separate option for changing the appearance of the subtitles and adding a speed slider?

**Comment by Dreamlinerm** [comment]
hmm, yes it is possibly ok, I will separate the two into speed slider and video modifications

**Comment by Dreamlinerm** [comment]
Added in version 1.1.33, will come to chrome later, firefox published.

**Comment by hokkaman** [comment]
Thanks!!😊
