### ISSUE TITLE
[BUG] Extension popup / menu is not displayed correctly in Microsoft Edge

### ISSUE THREAD

**Issue by NaLogo** [Dreamlinerm/Netflix-Prime-Auto-Skip#119]
### Describe the bug
The extension popup / menu does not size itself correctly when opened via the extension icon.
It appears as a narrow line, which renders the popup unusable.
This also happens with an otherwise empty profile (no other extensions, no nothing).

![IqQPQLe93Y](https://github.com/user-attachments/assets/65ecebbb-758f-4d9e-bf8d-9069d4b275ff)

### To Reproduce
1. Install extension
2. Click extension icon
3. Observe narrow popup

### Expected behavior
I'd expect the popup to appear in a size that makes its contents readable and usable.

### Background information:
 - Site: Any
 - Browser: Microsoft Edge
 - OS: Windows 10 22H2
 - Addon-Version: v.1.1.41
 - Console logs: Nothing. (Tested by visiting about:blank and then clicking the extension icon.)

**Comment by Dreamlinerm** [comment]
LOL I did not see that coming, why does the css work differently in chrome and Firefox I will try to fix immediately

**Comment by Dreamlinerm** [comment]
You should still be able to use the regular settings. If you right-click and click on options

**Comment by Dreamlinerm** [comment]
This was due to me trying to change the popup size on mobile. 
Fixed in c270470398f828f684f4cc09c5ac94d94a1b3c87 version 42
Edge update takes the longest like 2 days, chrome updated today.
![image](https://github.com/user-attachments/assets/db141e2c-61e2-406a-8a83-525b7027af3e)

**Comment by NaLogo** [comment]
Well, that was quick. Thank you! 🚀
