### ISSUE TITLE
[BUG] Skipping multiple Prime ads at the start of a video frequently stalls

### ISSUE THREAD

**Issue by pessimism** [Dreamlinerm/Netflix-Prime-Auto-Skip#120]
### Describe the bug
What feature is the bug regarding? e.g. Freevee ad
Skipping multiple Prime ads at the start of a video frequently stalls

### To Reproduce
Start a movie on Prime Video.  Ad skipping stops randomly before video loads.  started happening the last month or two.

### Expected behavior
2-6 ads are skipped, movie plays

### Background information:
amazon prime us/ca, both edge and firefox

**Comment by Dreamlinerm** [comment]
@pessimism do you think this is a us specific issue?

**Comment by Dreamlinerm** [comment]
You can also join the discord and write me directly btw.: https://discord.gg/5fBYathA7d

**Comment by Dreamlinerm** [comment]
I managed to replicate this issue on amazon.com with a vpn and will try to fix now.

**Comment by Dreamlinerm** [comment]
I think the problem is that you have a lot longer ads, they are 2mins wtf.
