### ISSUE TITLE
[BUG] Prime speed control frequently glitches out and stalls playback

### ISSUE THREAD

**Issue by pessimism** [Dreamlinerm/Netflix-Prime-Auto-Skip#121]
What feature is the bug regarding? e.g. Freevee ad
Prime speed control frequently glitches out and stalls playback. 1.1 usually okay but sometimes fails, 1.2 and up almost always fails

To Reproduce
Start some content on Prime Video.  Try to increase speed.  Video randomly hangs and requires a browser reload.  Started happening a month or two ago.

Expected behavior
Speed increases with slider movement, video plays.

Background information:
amazon prime us/ca, both edge and firefox

**Comment by Dreamlinerm** [comment]
Should be fixed in version 1.1.44, but I'm not totally sure reopen if not fixed.
