### ISSUE TITLE
[BUG] Subtitle desync on amazon.co.uk when uBlock origin enabled (Ublocks fault)

### ISSUE THREAD

**Issue by jennischofield** [Dreamlinerm/Netflix-Prime-Auto-Skip#124]
### Describe the bug
Amazon ad skip now desyncs subtitles (subtitles continue through the ad break, and are ahead by the length of the skipped ad)

### To Reproduce
Run any episode with subtitles and hit an ad break. When the ad is skipped, the subtitles will be ahead of the video/audio. This can be resolved by completely closing tab and opening amazon again.

### Expected behavior
Subtitles should be synched to audio/video.

### Background information:
 - amazon.co.uk
 - Seen on House M.D. (non-freevee show)
 - UK
 - Firefox
 - v1.1.53
[console-export-2024-12-10_20-16-11.txt](https://github.com/user-attachments/files/18085333/console-export-2024-12-10_20-16-11.txt)

**Comment by Dreamlinerm** [comment]
ah this was reported in the review comments. 
 The subtitles continue through the ad break that is very helpful to know. 
 Let me try if I can use the uk amazon page through a VPN. 
 Through the console log i can see that u use uBlock origin let me see if I can reproduce.

**Comment by Dreamlinerm** [comment]
![image](https://github.com/user-attachments/assets/ad9579bb-65fc-462b-b28c-4a1f0e870a53)
this guy said it somehow interferes with ublock origin so im gonna test that

**Comment by Dreamlinerm** [comment]
I could reproduce the problem on amazon.co.uk and not on the one im using and I confirmed the problem only occurs if uBlock origin is enabled.

**Comment by Dreamlinerm** [comment]
On my website this does not happen because uBlock blocks the ad before my extension can and my extensions block is more of a fallback if the ad domain is not registered in Ublock. 
I did this on purpose since I believe UBlock to be better than me a single dev compared to their 112 contributors.

**Comment by Dreamlinerm** [comment]
I tested only uBlock Origin without my extension enabled, and the video continues without any subtitles.
So ultimately I think it is Ublocks issue and u should open an issue in their GitHub, in my opinion.
Their ad skip in this case is actually worse than mine in this situation, who would have thought.

To fix this u can either disable my adskip on amazon prime only in the settings or disable Ublock origin on this website.

**Comment by jennischofield** [comment]
Thanks for the update, ublock defo didn't block prime ads for the longest time, so it must be new on their end. Thanks, I'll sort it on my end!
