### ISSUE TITLE
Infinite Loading on Prime Video

### ISSUE THREAD

**Issue by M3tR3mix** [Dreamlinerm/Netflix-Prime-Auto-Skip#17]
After watching an episode it skips to the next one but  the page starts to buffer for infinite time. Only way to fix this is reloading the page or disable the skip Selfads option. Brave browser if helps

**Comment by Dreamlinerm** [comment]
I have noticed that as well, will try to fix this and the subtitle issue.

**Comment by Dreamlinerm** [comment]
In my latest update, the infinite loading and subtitle issue should hopefully be resolved. If you have any problems, keep me posted

**Comment by Dreamlinerm** [comment]
Have been watching series, I'm closing the issues until more reports
