### ISSUE TITLE
Freevee: no skip when ads are triggered due to user interaction

### ISSUE THREAD

**Issue by timmeinerzhagen** [Dreamlinerm/Netflix-Prime-Auto-Skip#18]
## Description

When a user presses the "forward by 10 seconds" button which leads them to hit an ad marker or they manually choose a point in the video which lies behind an ad marker, then the ad will play anyway - it does not get skipped by this extension.

## Findings

This seems to be caused by the extension checking whether the video is currently playing before a skip. I would guess that the user interaction causes the video to be marked as "paused" for a short moment.

https://github.com/Dreamlinerm/Netflix-Prime-Auto-Skip/blob/147df8c32bddef2003419d901a7b3e34e3aaa7a5/chrome/skipper.js#L278
@Dreamlinerm It seems like you just [added this condition in the `v1.0.16` release ](https://github.com/Dreamlinerm/Netflix-Prime-Auto-Skip/commit/147df8c32bddef2003419d901a7b3e34e3aaa7a5#diff-6c71e865629b6031ba0eec7e3e7a053e5f702f8183b1bf90e8a62f91ae174d73R278). Was there a particular need for this? If not, can this condition be removed again?

**Comment by Dreamlinerm** [comment]
The reason i added the is playing check was there was/is a infinite loading issue the first time you watch a series, gonna try to use a diffrent fix for that

**Comment by Dreamlinerm** [comment]
Replaced it with video.currentTime > 0, that seems to fix it will publish the new version now

**Comment by Dreamlinerm** [comment]
thank you for reporting this issue, I hopefully fixed both issues in version 1.0.17. Thank you for the very detailed bug report.

**Comment by Dreamlinerm** [comment]
I think now there might be an ad before the series, but I'm not sure what a better check might be to not cause this non skipped ad issue.

**Comment by Dreamlinerm** [comment]
i think im gonna do a combinatino of currentTime>0 and !paused

**Comment by timmeinerzhagen** [comment]
> i think the problem is that on the first time the ad is separate to the video, so that's why if it tries to skip forward in the video it crashes. and if its not the first time the ads get abetted in the video.

I did some testing but I could not reproduce the crashing. On `v1.0.17` I only noticed that the preroll Freevee ad sometimes does not skip at all. When hovering over the Freevee ad that was not yet skipped, it immediately skips though. I guess the Ad time Text does not get generated until the user hovers, thus rendering and opening up the overlay.

> i think im gonna do a combinatino of currentTime>0 and !paused

Yeah that might work, but I still had some preroll Freevee ads that did not get skipped until I hovered over the video as described above. Not sure if there is an easy way to sumulate that behaviour

**Comment by Dreamlinerm** [comment]
> 

I think i might have fixed it in version .18, I did a lot of testing hope it works now, otherwise I will just accept the infinite loading I guess. In version .17 there is no infinite loading and every ad should be skipped now in .18 i hope. There is a possibility to simulate the behavior, but I hope it won't come to this.

**Comment by Dreamlinerm** [comment]
If you want to implement new features in the future or fix bugs i can invite you to collaborate if you want.
