### ISSUE TITLE
[FEATURE] [Prime] add label to show that ad got skipped, which might have also skipped some of the video

### ISSUE THREAD

**Issue by marcus-dev** [Dreamlinerm/Netflix-Prime-Auto-Skip#23]
Hello !

First, the plugin is really nice ! 

I use it for Amazon Prime in FireFox, and the skip is too fast in my opinion.
For exemple, when the intro is skipped, I really do not see any part of the intro. To a point where I am wondering if i am missing aon some actual content.

It would be nice to delay the skip by 1 or 2 seconds, so it is clear that something is skipped.
Adding a setting for such delay would also be appreciated.

**Comment by Dreamlinerm** [comment]
Hi

I added the watch intro button, which will show after a skipped intro on Amazon Prime. 

But I will consider to add the option of a delay since there also is no such button on Netflix for example. 
I think the default behaviour would stay the same tho and it would definitly be a setting.

**Comment by Dreamlinerm** [comment]
What is your opinion regarding the watched skipped intro button?

**Comment by marcus-dev** [comment]
Regarding the watch intro button, I would say that clicking on something is against the extension philosophy ;)
I just installed the extension so I cannot say more about day-to-day usage.

For my precise use case, I actually clicked on it and saw that I indeed missed a little part just before the intro, hence my request for a delay

**Comment by Dreamlinerm** [comment]
Yes clicking something is definitely against the philosophy which is why I added the button, in case you may want to watch the intro without disabling the feature and reenabling it afterwards.
Thanks for the review, btw.
This extension uses the Amazon function to skip intros, so if anything is skipped after the intro, it's amazons fault.

**Comment by Dreamlinerm** [comment]
Thanks for opening an Issue. Feedback is always appreciated.
Thanks for the coffee bro, that's the first donation I received ever cool.
For the ads that's another story, obviously there is no function for that XD. There I need to fix a bug still as you can see in the issues.

**Comment by marcus-dev** [comment]
I see what you mean for amazon's fault :D 
Maybe I stumbleded upon an edge case, In the mean time do you want me to close this thread ?

Well then it was a pleasure being the first donator 🥇

**Comment by Dreamlinerm** [comment]
Hmm i might consider adding like a label or sth for skipped ads, to show that it was skipped, because there I cannot gurantee that parts of the video did not get spipped since it does not use the functionality of the site. So I will rename it.

**Comment by marcus-dev** [comment]
Well, my original post was all about the intro, not add.
But as I said, I'll just live with it for now to see if it is a recurring issue

**Comment by Dreamlinerm** [comment]
Then I will open another issue for the ad label, and you can close the issue or keep me updated if it's a reoccurring issue or the delay might still be sensible. I will close it myself after a month.
