### ISSUE TITLE
White screen after load after prime video changes.

### ISSUE THREAD

**Issue by DerpDerpingtonIsHere** [Dreamlinerm/Netflix-Prime-Auto-Skip#32]
**Describe the bug**
Since Amazon prime video updated it's looks it loads for a few seconds then turns to a blank white page (See video for context)
**To Reproduce**
1. Go to 'prime video'
2. Wait for 'Screen to turn white'

**Expected behavior**
To load and not turn to a white screen?

**Screenshots**
https://imgur.com/a/9eyNJpN VIDEO

**Desktop (please complete the following information):**
 - OS: WIndows 11 version 22H2 Build: 22621.1485
 - Browser Chromium
 - Version 111.0.5563.147 (Official Build) (64-bit)

**Additional context**
This behavior stops if I go to Netflix/Prime auto-skip extension and disable the Amazon automations.

**Comment by Dreamlinerm** [comment]
hmm could you try which automation specifically causes this, i have not seen this behavior and I did not change any amzon functions in the last updates. which addon version do you have specifically

**Comment by Dreamlinerm** [comment]
you can turn off specific features in the individual settings

**Comment by Dreamlinerm** [comment]
could you maybe also privide the url like are you using amazon.com or a different one.

**Comment by Dreamlinerm** [comment]
The feature that is expect to be the problem is Remove paid content in the individual settings, can you turn it off and see if its the problem.

**Comment by DerpDerpingtonIsHere** [comment]
https://www.amazon.com/gp/video/storefront/ref=atv_pr_sw_sc is the URL I use, Also can confirm it is the "remove paid content" that is causing the issue. I will keep testing to see if it continues to work.

**Comment by Dreamlinerm** [comment]
Hmm, I can envision a fix for that already OK that was already really helpful.

**Comment by Dreamlinerm** [comment]
If you see that the next browser version is published, this bug should be fixed and please see and reply here if it got fixed. Chrome takes like a day to publish a new version, Firefox is basically instant.

**Comment by Dreamlinerm** [comment]
Seems like chrome already published the new version 32 pretty quick, so update the add-on and see if the problem is fixed please.

**Comment by DerpDerpingtonIsHere** [comment]
> Seems like chrome already published the new version 32 [8316504](https://github.com/Dreamlinerm/Netflix-Prime-Auto-Skip/commit/8316504d7bed7f74f23d6d65a68e05b67e8487a8) pretty quick, so update the add-on and see if the problem is fixed please.

Problem seems to be fixed. I will mark this as closed. Will keep testing for changes. Thank you for such a quick fix!
