### ISSUE TITLE
[BUG]Buffering when trying to skip ad

### ISSUE THREAD

**Issue by ghost** [Dreamlinerm/Netflix-Prime-Auto-Skip#33]
**Describe the bug**
When watching shows that have ads (for instance BuzzFeed Unsolved: Supernatural, it will switch to the next episode, It will click the skip ad button but will cause it to sit and buffer.

**To Reproduce**
1. Go to a show with ads like 'BuzzFeed Unsolved: Supernatural'
2. Click on 'N/A'
3. Scroll down to 'N/A'
4. See error N/A
5. Wait for an episode to end, then when it switches to a new episode, it will click the skip ad button and cause it to buffer at times. This does not happen every time, I think it may be detecting the auto skipping feature since it happens almost instant. Maybe have a small delay on it could fix the issue?

**Expected behavior**
It should skip the ad and go directly into the episode.

**Screenshots**
N/A

**Background information:**
 - URL: [Amazon.com]
 - OS: [Windows 11 22H2 latest]
 - Browser [Chromium Version 111.0.5563.147 (Official Build) (64-bit)]
 - Addon-Version [Version: 1.0.32]

**Additional context**
N/A If you need me to do anything else just ask and I will try my best. I love this Extension and would like to help make it as easy as possible for you to fix any issues that may arise.

**Comment by Dreamlinerm** [comment]
Let me see if buzzfeed unsolved supernatural is special in some kind of way or its a general problem. Your browser or website seems to have some special layout different from the other people since they did not report these problems. I live in europe so im awake now.

**Comment by Dreamlinerm** [comment]
I could certainly add a delay when at the beginning of an episode or sth like that let me see if I can replicate the bug.

**Comment by Dreamlinerm** [comment]
I cant come across every bug myself, so its very helpful that you are opening these issues. For example one guy had the problem that after skipping an ad his subtitles were disabled that was a weird issue man, but that one i confirmed myself.

**Comment by Dreamlinerm** [comment]
I cant see to replicate the issue, can you make a internet speed test at https://www.speedtest.net/ and send it, the buffering may be related to how fast you can load the video in comparison to how fast it skips or sth.

**Comment by DerpDerpingtonIsHere** [comment]
> I cant see to replicate the issue, can you make a internet speed test at https://www.speedtest.net/ and send it, the buffering may be related to how fast you can load the video in comparison to how fast it skips or sth.

Sure thing https://i.imgur.com/KHuZV7k.png

**Comment by Dreamlinerm** [comment]
Damn thats faster than mine so thats definitely not the problem then.

**Comment by Dreamlinerm** [comment]
If you are available I can debug this with you together on discord Dreamliner#0104 is my acc.

**Comment by DerpDerpingtonIsHere** [comment]
![0Ww4cXg](https://user-images.githubusercontent.com/12119604/229705308-d2d0be09-51fe-47d5-80c6-6c9d16ae44c7.png)
