### ISSUE TITLE
Just wondering if this was based off of YouTube sponsor block.

### ISSUE THREAD

**Issue by Bennett-Fourr** [Dreamlinerm/Netflix-Prime-Auto-Skip#36]

**Comment by Dreamlinerm** [comment]
Haha, I did not copy any code, but the Settings menu design was definitely inspired as you can see. I can change it, if it is too similar. The previous settings I made did not have a normal menu, but a menu similar to the popup which became a little too complicated

**Comment by Dreamlinerm** [comment]
I am just a single guy, if you have any improvement suggestions I change it.

**Comment by Dreamlinerm** [comment]
For example, I could make this a more traditional hamburger menu similar to this
![image](https://user-images.githubusercontent.com/90410608/237045201-b9dae341-7afd-448b-aa17-555b6535cc69.png)

**Comment by Dreamlinerm** [comment]
You just gave me the idea to add icons to the menu, I will do that.

**Comment by Bennett-Fourr** [comment]
Cool.
