### ISSUE TITLE
[FEATURE]Please support up to 2x speed on Prime Video.

### ISSUE THREAD

**Issue by hokkaman** [Dreamlinerm/Netflix-Prime-Auto-Skip#37]
The playback speed slider in Prime Video currently supports up to 1.5x speed.
However, I find 1.5x speed insufficient.
Is it possible to extend the slider to support up to 2x speed?

**Comment by Dreamlinerm** [comment]
Ok no problem

**Comment by Dreamlinerm** [comment]
uploaded new version

**Comment by hokkaman** [comment]
Thank you!!😊
