### ISSUE TITLE
No longer working for Amazon Prime [BUG]

### ISSUE THREAD

**Issue by vampiregoat699** [Dreamlinerm/Netflix-Prime-Auto-Skip#38]
When watching a movie on prime it would skip all commercials now it no longer does it and you have to manually skip the movies

**Comment by Dreamlinerm** [comment]
What commercials do you mean the ads in front of the videos? or the freevee ads?

**Comment by Dreamlinerm** [comment]
Also make sure that this feature is still enabled in the settings.

**Comment by Dreamlinerm** [comment]
I checked on my device the functions are still working which domain are you using, this also may differ. Amazon.com?

**Comment by vampiregoat699** [comment]
Newest version installed, Freevee ads not skipping as it did before I use Amazon.com on Firefox 113.0.2 Windows 10.

**Comment by Dreamlinerm** [comment]
For the freevee stuff its region locked, I am trying to install some vpn to check if there is a problem on Amazon.com

**Comment by Dreamlinerm** [comment]
Amazon apparently knowns I am using a VPN and doesnt let me start watching videos oof. Would you be down to show me the issue on this discord server? https://discord.gg/kuHraCc7
