### ISSUE TITLE
Stays stuck at ad screen on Netflix[BUG]

### ISSUE THREAD

**Issue by zayn-k** [Dreamlinerm/Netflix-Prime-Auto-Skip#40]
The extension is able to skip ads but stays stuck on the last ad screen instead of getting back to the show.
This is on Netflix.
Browser is Opera.
This happens to ads in the middle of the show. The ad before the intro is skipped just fine.

**Comment by Dreamlinerm** [comment]
I have not tried opera. Let me see if i can fix

**Comment by Dreamlinerm** [comment]
I just tested it on the Opera browser and I dont seem to get this issue, maybe I can fix it still.

**Comment by zayn-k** [comment]
This issue was observed on Opera 95 and Chrome 109. Tested on Chrome 114 and observed to be working but has some buffering in the middle of ads. I can live with that 👍
