### ISSUE TITLE
Netflix ad skip audio/video sync

### ISSUE THREAD

**Issue by revint** [Dreamlinerm/Netflix-Prime-Auto-Skip#43]
**Bug**
Sometimes after netflix ad skipping the audio and video will no longer be synced, a refresh of the browser fixes the sync until the next one or two ad skips.

**To Reproduce**
1. open chrome and go to netflix
2. play a netflix video and wait for a few ads to play
3. start noticing audio/video sync issues

**Expected behavior**
Audo/video is synced after ads

**Background information:**
 - URL: netflix.com
 - OS: windows 10
 - Browser chrome
 - Addon-Version 1.0.45

**Comment by Dreamlinerm** [comment]
I will look into it

**Comment by Dreamlinerm** [comment]
I am not sure if I can fix this. It does not seem to happen on firefox, but I think I was able to confirm the the audio will go slightly off snyc.

**Comment by revint** [comment]
Firefox seems to work but i notice lower quality video, probably a difference in DRM between chrome and firefox. Thanks for looking into it.

**Comment by Dreamlinerm** [comment]
Can you fix the audio/video sync by switching the language forth and back. I am trying of solutions to fix this, because fast forwarding with the neflix functions itself does not fix it

**Comment by Dreamlinerm** [comment]
I am trying to slow down the forwarding before the ad is over but that does not ssem to help resolve the issue.

**Comment by Dreamlinerm** [comment]
This might be a general Chrome issue where forwarding makes the browser lag
https://support.google.com/chrome/thread/5716937/how-do-you-actually-resolve-the-audio-and-video-sync-issue-on-chrome?hl=en

**Comment by Dreamlinerm** [comment]
I just tried forwarding normally and it also misaligns the audio and video so I think this a cant fix issue.

**Comment by revint** [comment]
Reading the link you posted, they where saying Edge worked? Would it be possible to get this addon added to Edge, to take advantage of the better video quality it provides over Firefox? Other than that this ticket can be closed as wont fix.

**Comment by Dreamlinerm** [comment]
You can just download the normal Chrome add-on on edge.
