### ISSUE TITLE
Edge browser fails to add skip Netflix

### ISSUE THREAD

**Issue by revint** [Dreamlinerm/Netflix-Prime-Auto-Skip#51]
**Describe the bug**
When you install the Netflix-Prime-Auto-Skip addon from the chrome extension store in the Edge browser, then play a netflix video, ads will fail to skip.

**To Reproduce**
1. open microsoft edge browser
2. go to chrome extension website
3. install netflix-prime-auto-skip addon
4. go to netflix and play a video
5. ads fail to skip in videos

**Expected behavior**
Ads should skip

**Background information:**
 - URL: netflix.com
 - OS: windows 10
 - Browser Edge
 - Addon-Version 1.0.47

**Comment by Dreamlinerm** [comment]
You are correct, I dont know why it does that

**Comment by Dreamlinerm** [comment]
I seems that on edge the max playbackrate is 3x which is annoying it seems

**Comment by Dreamlinerm** [comment]
"Fixed" in version 49 by only forwarding by 3x
