### ISSUE TITLE
[BUG]Prime Video does not add speed slider.

### ISSUE THREAD

**Issue by hokkaman** [Dreamlinerm/Netflix-Prime-Auto-Skip#52]
**Describe the bug**
The speed slider is not added in Prime Video even though the speed slider is turned on in the extension settings.

**To Reproduce**
1. Enable "Shared Settings" → "Add Speed Slieder" in the settings screen of the extension.
2. Play videos on Prime Video.
3. Speed slider not added to player controls

**Expected behavior**
A speed slider will be added.

**Background information:**
 - URL: amazon.co.jp
 - OS: Windows 11
 - Browser Chrome
 - Addon-Version v.1.0.49

**Comment by Dreamlinerm** [comment]
hmm the japan website may be different. I can use vpn to check

**Comment by Dreamlinerm** [comment]
apparently amazon changed their layout on my website aswell I will fix the speed slider immidiatly

**Comment by Dreamlinerm** [comment]
I dont allways watch streaming services so its great that you reported this issue thanks.

**Comment by Dreamlinerm** [comment]
I fixed it i will publish the new version today.

**Comment by hokkaman** [comment]
Thanks for the fix!😊

**Comment by Dreamlinerm** [comment]
I uploaded the new version It's already online in Firefox and in chrome It's when they finish review

**Comment by Dreamlinerm** [comment]
Fixed in version v.1.0.50

**Comment by Dreamlinerm** [comment]
Its updated in Chrome aswell
