### ISSUE TITLE
[BUG] The plugin stopped working on Chrome 115.0.5790.170 (Official Build)

### ISSUE THREAD

**Issue by atiqullah-ahmadzai** [Dreamlinerm/Netflix-Prime-Auto-Skip#54]
Its been several days the plugin is not working, is it only me or everyone?
I am using Chrome, Netflix.

**Comment by Dreamlinerm** [comment]
I will check if it still works

**Comment by Dreamlinerm** [comment]
What excactly is not working?

**Comment by Dreamlinerm** [comment]
Can you look into the console using the button F12 and see if there are any error and maybe send a screenshot if there are any?. maybe you just disabled Netflix functions in the settings.

**Comment by jason-1337** [comment]
Stopped working for me as well both in Chrome and Firefox. Ads just play at normal speed regardless of settings, however it is possible to speed them up manually using the slider.

Errors in the console don't seem to be related to the extension but here they are anyway.

Firefox:

XML Parsing Error: not well-formed
Location: https://www.netflix.com/msl/playapi/cadmium/licensedmanifest/1?reqAttempt=1&reqName=prefetch/licensedManifest&clienttype=akira&uiversion=vbcc15d45&browsername=firefox&browserversion=116.0.0&osname=windows&osversion=10.0
Line Number 1, Column 1: [1:1:1](https://www.netflix.com/msl/playapi/cadmium/licensedmanifest/1?reqAttempt=1&reqName=prefetch/licensedManifest&clienttype=akira&uiversion=vbcc15d45&browsername=firefox&browserversion=116.0.0&osname=windows&osversion=10.0)

Chrome:

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT         geolocation.onetrust…b/v1/geo/location:1 

DevTools failed to load source map: Could not load content for chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT

**Comment by Dreamlinerm** [comment]
I fixed it netflix changed the css class of the ad text

**Comment by jason-1337** [comment]
cool, when is the update coming out?

**Comment by Dreamlinerm** [comment]
Im uploading the new version right now so firefox pretty much immediatly chrome maybe 1-3hours

**Comment by Dreamlinerm** [comment]
Closed with version 1.0.51

**Comment by Dreamlinerm** [comment]
Closed with version v.1.0.51 in commit 9f11340
