### ISSUE TITLE
[FEATURE] Add "Watch Credits" option for Netflix. 

### ISSUE THREAD

**Issue by pablo-01** [Dreamlinerm/Netflix-Prime-Auto-Skip#57]
Add "Watch Credits" toggle - this would work like "Skip Credits" but instead of skipping credits it would allow for credits to roll/continue.

**Comment by Dreamlinerm** [comment]
oh, wow thats a great idea OK I will do that

**Comment by Dreamlinerm** [comment]
I think this feature is not that necessary on Amazon Prime since they wait for 10sec for the automatic skip credits, but I will do it to keep the settings consistent

**Comment by Dreamlinerm** [comment]
Added in version v.1.0.54
