### ISSUE TITLE
[BUG] Skipping goes too far in Prime in Edge

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [Dreamlinerm/Netflix-Prime-Auto-Skip#61]
**Describe the bug**
Skipping goes too far in Prime in Edge

**To Reproduce**
Use the extension with prime in edge.

**Expected behavior**
End right after the ad

**Comment by Dreamlinerm** [comment]
hmm. I will check this. Which browser?

**Comment by ErfolgreichCharismatisch** [comment]
Edge

**Comment by Dreamlinerm** [comment]
hmm you are correct it seems like its skipping more than the ad on edge, while on chrome it doesnt. I usually only test chrome and firefox.

**Comment by ErfolgreichCharismatisch** [comment]
Was jetzt?

**Comment by Dreamlinerm** [comment]
Bin gerade am Versuchen am fixen. versuche ne sekunde nach dem überspringen zu warten etc.

**Comment by Dreamlinerm** [comment]
I think I managed to fix it and will release the new version later

**Comment by Dreamlinerm** [comment]
I uploaded the new Chrome version and it should update soon. Closed with 525f8ae8eac0fce6d9218292ff0819a94e90c8a0

**Comment by ErfolgreichCharismatisch** [comment]
Wie komme ich an die neue Version in Edge, geht das automatisch?

**Comment by Dreamlinerm** [comment]
ja, das geht irgendwann automatisch in den nächsten tagen. Chrome muss erstmal das update überprüfen. Wende die neue Version schon früher haben willst, kannst du aber auch die neue Version hier herunterladen: https://github.com/Dreamlinerm/Netflix-Prime-Auto-Skip/blob/main/chrome/web-ext-artifacts/streaming_enhanced_netflix_disney_prime_video-1.0.58.zip

**Comment by Dreamlinerm** [comment]
![image](https://github.com/Dreamlinerm/Netflix-Prime-Auto-Skip/assets/90410608/6140e267-a002-4c14-8ae0-bdffc7ea7004)

**Comment by Dreamlinerm** [comment]
its updated on edge i checked
