### ISSUE TITLE
[Streaming Service] Add Star+

### ISSUE THREAD

**Issue by djgerman10** [Dreamlinerm/Netflix-Prime-Auto-Skip#63]
star plus comes from the Disney family I hope you can add it too
[https://www.starplus.com](https://www.starplus.com)

**Comment by Dreamlinerm** [comment]
I can but which country (need to know for vpn) and i need an acc prob. To first program it you can send me downloaded pages with the addon https://chrome.google.com/webstore/detail/singlefile/mpiodijhokgodhhofbcjdecpffjipkle
 but i certainly to test it i will need to test myself.

**Comment by Dreamlinerm** [comment]
I did it like that when someone rewuested hotstar

**Comment by Dreamlinerm** [comment]
Features that require a snapshot with single file:
* Skip intro button
* Skip Credits card/button

any other feature you want added like ads e.g.

**Comment by Dreamlinerm** [comment]
Added in version 1.0.89

**Comment by Dreamlinerm** [comment]
@djgerman10 I would have added it sooner if you would have responded another guy wrote to me
