### ISSUE TITLE
[BUG] Netflix skip ads

### ISSUE THREAD

**Issue by Fede14it** [Dreamlinerm/Netflix-Prime-Auto-Skip#65]
**Describe the bug**
Skip ads on Netflix when ad finish the film go over 10 second more or less

**To Reproduce**
Skip an ad and the film get speed after the ad for other 10/20 seconds

**Expected behavior**
when the ad finish he have to slow instant

**Screenshots**
If applicable, add screenshots

**Background information:**
 - URL: netflix.com
 - OS: Windows
 - Browser Chrome
 - Addon-Version 1.0.59

**Additional context**

**Comment by Dreamlinerm** [comment]
hmm, I dont have the Netflix ad tier, I will check the bug out when I have some time

**Comment by Fede14it** [comment]
If u want we can speak in discord and check together.
Are you available on Thursday?

Il giorno lun 23 ott 2023 alle ore 22:13 Dreamliner <
***@***.***> ha scritto:

**Comment by Dreamlinerm** [comment]
yes I have some time on Thursday https://discord.gg/g7QG3C3S

**Comment by Dreamlinerm** [comment]
closed with version 60
