### ISSUE TITLE
[BUG] "Auto pick last profile" not working on Netflix

### ISSUE THREAD

**Issue by Buesra24** [Dreamlinerm/Netflix-Prime-Auto-Skip#77]
**Describtion of bug:**

 - When I first open Netflix with the extension and its Netflix-settings enabled, I'm still asked to pick a profile ("Who's watching?").

**To Reproduce:**

 - On both Chrome and Firefox (with the extension & Netflix-settings enabled and a profile chosen via "User"), simply enter Netflix.

**Expected behavior:**

 - Profile chosen via "User" in Netflix-settings should automatically be picked.

**Background information:**
 - Exact URL: https://www.netflix.com/browse
 - OS: Windows 11
 - Browser: Chrome (v120.0.6099.130, 64-bit) & Firefox (v121.0, 64-bit)
 - Addon-Version: v.1.0.72 on both browsers

**Comment by Dreamlinerm** [comment]
What does it say under user here under the Netflix tab:
![image](https://github.com/Dreamlinerm/Netflix-Prime-Auto-Skip/assets/90410608/7e088809-2fcd-45b3-a065-ef425a6d2f97)

**Comment by Dreamlinerm** [comment]
> **Describtion of bug:**
> 
>     * When I first open Netflix with the extension and its Netflix-settings enabled, I'm still asked to pick a profile ("Who's watching?").
> 
> 
> **To Reproduce:**
> 
>     * On both Chrome and Firefox (with the extension & Netflix-settings enabled and a profile chosen via "User"), simply enter Netflix.
> 
> 
> **Expected behavior:**
> 
>     * Profile chosen via "User" in Netflix-settings should automatically be picked.
> 
> 
> **Background information:**
> 
>     * Exact URL: https://www.netflix.com/browse
> 
>     * OS: Windows 11
> 
>     * Browser: Chrome (v120.0.6099.130, 64-bit) & Firefox (v121.0, 64-bit)
> 
>     * Addon-Version: v.1.0.72 on both browsers

It may be easier to look at your browser directly over discord if you prefer: https://discord.gg/7us76ErE

**Comment by Buesra24** [comment]
@Dreamlinerm Oh, that seems to be it! My name has an "ü" letter in it (Turkish origin), so the extension doesn't seem to be able to handle it. It seems to be working fine when I try it with another profile, but with the profile containing the special letter ("Büsra") it shows up like this: 

![image](https://github.com/Dreamlinerm/Netflix-Prime-Auto-Skip/assets/51192546/30af66d0-3a6c-4a69-8921-775f88df1046)

The "- Account & Setting" addition also only shows up when I use this profile; with the others it only shows the name there. Probably one of the symbols breaking the pattern of where that piece of code was supposed to end, possibly?
I don't know how complicated it would be to allow for more kinds of letters, but either way I can just change the name to something else to get it to work, so thank you! (At least it'll be an easy fix for people with similar issues in the future :D)

**Comment by Buesra24** [comment]
That's kinda funny; my name written fully correctly is "Büşra" and since I live in Germany and my keyboards don't have that "ş" letter (and it ends up breaking lots of things), I always just use "Büsra" whenever a system allows it, which is why I didn't even think to try using a different name :D (once, that annoying letter broke my local Covid testing center's software to the point where I stood around for 45mins with a positive swab test without it registering me for my follow-up PCR test, until they finally tried it without the letter and it worked :D there was no warning the letter wasn't supported, sadly - we had to find out ourselves)

**Comment by Dreamlinerm** [comment]
Just doing it for the German letters is easy, and I have a fix, but I am checking if there is an easy general solution. Thas really funny man yea i would not use any special characters either and even sometimes the ö still breaks things around here lol

**Comment by Buesra24** [comment]
Nvm; I just tried it with a different name without any special characters and it still doesn't work and show the extra words after the name; I'll try out some more stuff (profile pic?) and get back to you.

**Comment by Dreamlinerm** [comment]
The special characters are definitely a problem. don't know if there is a second one.

**Comment by Dreamlinerm** [comment]
![image](https://github.com/Dreamlinerm/Netflix-Prime-Auto-Skip/assets/90410608/b4d83e2f-26da-4134-ba19-13575765469d)
I managed to fix it. Works pretty good. Dunno if there is a second issue

**Comment by Buesra24** [comment]
It's almost like this permanently messed something in my browser's code up (then again how could it?)

With only "B" as the name, I tried the following:
- Changed the picture
- Deleted "- Account & Setting" in the .json file of the account backup (it just gets added back in the second I enter the profile)
- Reinstalled the entire extension and added this changed .json file
- Reset the extension to default
- Reinstalled the entire extension and tried it with a clean profile

But every time it just keeps going back to adding "- Account & Setting" and refusing to auto pick the account
Super weird

This is the General part of the .json file btw:
"General":{"profileName":"B","profilePicture":"https://occ-0-4416-4415.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABaO2DDm9-aGwM86BKPJSY73LjQjgtdpnDF50yQXbL3xjGP5CQ0mnUoQUCRzMxgqZgDFMKwmVDulVowudnizPzakIxlwr8e8.png?r=60a","sliderSteps":1,"sliderMin":5,"sliderMax":20,"filterDub":true,"filterQueued":true}

**Comment by Dreamlinerm** [comment]
You wanna show me on discord? https://discord.gg/GzEZDTFX

**Comment by Dreamlinerm** [comment]
ah I think i know how to fix it. the second issue.

**Comment by Dreamlinerm** [comment]
I fixed both bugs in version 73 that I uploaded right now.

**Comment by Dreamlinerm** [comment]
Btw. if you are on the home page it will set the name again, if you change it manually.

**Comment by Dreamlinerm** [comment]
There is an easy way to check if it works goto edit profile and click finish. Then it will autopick again

**Comment by Buesra24** [comment]
Yes, that worked wonderfully!
Had to wait a bit for both the Firefox and Chrome stores to catch up with the update but it's working exactly as intended on both browsers now. 
Thank you very much! 

I'm really curious what is causing my profile to keep getting that extra text though, it's so strange that it only happens on mine and not my sisters'... I looked around in the console logs etc as well, but nothing really showed up; I guess I'll have to live with not knowing :D

**Comment by Dreamlinerm** [comment]
when I read out the profile name on the home page it says - Account & settings at the end. I remove everything after the -, but I think your browser uses a different unicode minus, which is why it did not get removed, but looks the same bruh.

**Comment by Buesra24** [comment]
> There is an easy way to check if it works goto edit profile and click finish. Then it will autopick again

Yeah, that's how I've been testing it for myself - it got really annoying closing and opening the browser only to find the other profiles autopicked again :D (well, annoying that it works for them and not me, that is)

**Comment by Buesra24** [comment]
> when I read out the profile name on the home page it says - Account & settings at the end. I remove everything after the -, but I think your browser uses a different unicode minus, which is why it did not get removed, but looks the same bruh.

That's strange, I specifically tried it on two different browsers just in case something weird like this was going on with one of the browsers... Could be an issue with my PC though I guess; it coincidentally being different on two browsers seems kinda unlikely otherwise.

**Comment by Dreamlinerm** [comment]
> > when I read out the profile name on the home page it says - Account & settings at the end. I remove everything after the -, but I think your browser uses a different unicode minus, which is why it did not get removed, but looks the same bruh.
> 
> That's strange, I specifically tried it on two different browsers just in case something weird like this was going on with one of the browsers... Could be an issue with my PC though I guess; it coincidentally being different on two browsers seems kinda unlikely otherwise.

I don't know anyway I added the other - replace if it does not do anything, it doesn't matter 😂
