### ISSUE TITLE
[FEATURE] Is it possible to make a Docker image or similar?

### ISSUE THREAD

**Issue by speed007** [Dreamlinerm/Netflix-Prime-Auto-Skip#82]
Is it possible to make this to be used in a docker image as a lot of people use docker for media servers and something like this would help immensely, we already have pihole and Adguard Home for docker and this may be integrated into one of those servers..? 
Fantastic work nevertheless!👍👍

**Comment by Dreamlinerm** [comment]
hmm I will think if this is possible

**Comment by speed007** [comment]
> hmm I will think if this is possible
Thank you! Much appreciated.

**Comment by Dreamlinerm** [comment]
It is possible for the adblock part, but not for the rest. I will try to develop a mobile app first before I try to attempt this.

**Comment by k3v1nwrld** [comment]
> It is possible for the adblock part, but not for the rest. I will try to develop a mobile app first before I try to attempt this.

Hey, are there certain domains you block (for Netflix)??? Cuz if it's that it may be easier to explain how to block them with PiHole/AdGuardHome

**Comment by Dreamlinerm** [comment]
> > It is possible for the adblock part, but not for the rest. I will try to develop a mobile app first before I try to attempt this.
> 
> Hey, are there certain domains you block (for Netflix)??? Cuz if it's that it may be easier to explain how to block them with PiHole/AdGuardHome

no the Netflix ad servers are the same as the content servers, on Netflix a image is therefore impossible. This would  only be possible on amazon prime and disney i think
