### ISSUE TITLE
[BUG] disney+ some videos not loading

### ISSUE THREAD

**Issue by Flolant** [Dreamlinerm/Netflix-Prime-Auto-Skip#86]
### Describe the bug
Some Series not Loading. Disney+ Logo is Playing but nothing more.
This is only happening when you start a new Episode.

### To Reproduce
Watch "Percy Jackson: Die Serie"

### Expected behavior
Video should load like at the most of the other Content.

### Background information:
 - Exact URL(includes show): https://www.disneyplus.com/de-de/video/e23358d5-3276-457d-b01a-651ec38937a5
 - Country: Germany
 - Browser chrome
 - Addon-Version 1.0.83

**Comment by Dreamlinerm** [comment]
IS this only happening if you come from the previous episode or if you come from the home page to watch a fresh episode.

**Comment by Flolant** [comment]
Both.
Even when I start watching with the link above.

**Comment by Dreamlinerm** [comment]
hmm also vllt kann du mir das problem über discord zeigen?https://discord.gg/ahwQrxjY
Ich denke das liegt daran, dass wenn das video noch keine 5 sekunden hat ich zurückspule damit der skip intro knopf erscheint.
![image](https://github.com/Dreamlinerm/Netflix-Prime-Auto-Skip/assets/90410608/f7e2cc35-519e-48fd-8327-02f93bbc3534)

**Comment by Dreamlinerm** [comment]
To temporarily fix you can disable the skip intro feature for Disney in the advanced settings

**Comment by Flolant** [comment]
temporarily fix is working

did this maybe happen because of the disney+ original intro?
because only the newer ones are affected atm afaik

**Comment by Dreamlinerm** [comment]
Yes probably, I don't have this original intro on my browser, so that's probably it.

**Comment by Flolant** [comment]
which browser are you using?
is it possible to skip that intro too?

**Comment by Dreamlinerm** [comment]
firefox

**Comment by Dreamlinerm** [comment]
ah I have ublock origin enabled on my browser, which blocks the original show I can see the issue now

**Comment by Dreamlinerm** [comment]
fixed in verison 1.0.83

**Comment by Dreamlinerm** [comment]
There is another bug which i fix in 85
