### ISSUE TITLE
What else I have noticed...

### ISSUE THREAD

**Issue by MurphyDoe0815** [Dreamlinerm/Netflix-Prime-Auto-Skip#89]
i'm watching **freevee** and the jump from the advert to the next one works. i've noticed that it skips at least 2 minutes and you miss the connection and don't know what's going on anymore.

Hardware: raspi 4 ,4 gb , raspian os 32 bit, v1.088

**Comment by Dreamlinerm** [comment]
hmm the adskip should stop 1 second before the ad is over, maybe you can send the console.logs if this happens again

**Comment by Dreamlinerm** [comment]
Another guy on a raspberry pi , had the problem that the performance was not high enough, maybe this is the case here. I maybe could improve the performance more.

**Comment by Dreamlinerm** [comment]
If this is still appearing you can also show me over discord

**Comment by MurphyDoe0815** [comment]
I was already thinking the same thing. 
he was already complaining about an additional tab.

but i got rid of it again because i could skip netflix up to 10% without any problems. amazon without any problems and disney completely wipes out my network adguard. 

so why not with netflix and amazon?
freevee doesn't even begin to complain - but it's just too big to skip ? maybe because the signs there are not interpreted correctly by the tool ? 

i will try everything with my laptop.
maybe someone has experience with raspi 5 or something similar ?
