### ISSUE TITLE
[BUG]Issue with Hotstar India Next Episode Skip

### ISSUE THREAD

**Issue by alok1nanda** [Dreamlinerm/Netflix-Prime-Auto-Skip#94]
### Describe the bug
Chrome Tab crashes when it tries to skip to the next video in Hostar

### To Reproduce
Play any video on hotstar.com and wait for the next episode icon to appear

### Expected behavior
It skips to the next episode without crashing

### Background information:
 - Exact URL(includes show): (https://www.hotstar.com/in/shows/flex-x-cop/1260166028/episode-1/1260166069/watch)
 - Country: [India]
 - Browser [Chrome]
 - Addon-Version [1.0.96]
 - Save the console logs in a txt and upload them here with ctrl+v or dragging

**Comment by Dreamlinerm** [comment]
hmm OK I have to get a hot star account to check this issue, I ask the last guy who give it to me, meanwhile you can disable the skip credits feature for disney, until it is fixed.

**Comment by alok1nanda** [comment]
[Watch Flex x Cop S1 Episode 1 on Disney_ Hotstar (3_25_2024 11_50_30 PM).zip](https://github.com/Dreamlinerm/Netflix-Prime-Auto-Skip/files/14747997/Watch.Flex.x.Cop.S1.Episode.1.on.Disney_.Hotstar.3_25_2024.11_50_30.PM.zip)

I tried using the extension,but the new episode button is not getting saved there...

I tried to collect errors for your extension and got the below error..

![image](https://github.com/Dreamlinerm/Netflix-Prime-Auto-Skip/assets/64365715/372918bc-f094-41ec-a5e2-f804ca07d2f5)

**Comment by Dreamlinerm** [comment]
> [Watch Flex x Cop S1 Episode 1 on Disney_ Hotstar (3_25_2024 11_50_30 PM).zip](https://github.com/Dreamlinerm/Netflix-Prime-Auto-Skip/files/14747997/Watch.Flex.x.Cop.S1.Episode.1.on.Disney_.Hotstar.3_25_2024.11_50_30.PM.zip)
> 
> I tried using the extension,but the new episode button is not getting saved there...
> 
> I tried to collect errors for your extension and got the below error..
> 
> ![image](https://private-user-images.githubusercontent.com/64365715/316612150-372918bc-f094-41ec-a5e2-f804ca07d2f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzOTE2MTcsIm5iZiI6MTcxMTM5MTMxNywicGF0aCI6Ii82NDM2NTcxNS8zMTY2MTIxNTAtMzcyOTE4YmMtZjA5NC00MWVjLWE1ZTItZjgwNGNhMDdkMmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE4MjgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNzkwZDc2MTRmZGQ1OWQ0YTgwZDBhNjc0N2NhMDJkZjA1OWE4NDVjYjczMDU2YTc3NzcxZjAwYWE4NTBlMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lIu0qf5EbFMiFS5oRmaaxwZirAoHcNfx3CozyTzuMLE)

can you call me over discord and I try to if I can fix this issue together? https://discord.gg/5fBYathA7d

**Comment by Dreamlinerm** [comment]
can you send me the console.logs when the issue appers. you can see them pressing F12

**Comment by Dreamlinerm** [comment]
> [Watch Flex x Cop S1 Episode 1 on Disney_ Hotstar (3_25_2024 11_50_30 PM).zip](https://github.com/Dreamlinerm/Netflix-Prime-Auto-Skip/files/14747997/Watch.Flex.x.Cop.S1.Episode.1.on.Disney_.Hotstar.3_25_2024.11_50_30.PM.zip)
> 
> I tried using the extension,but the new episode button is not getting saved there...
> 
> I tried to collect errors for your extension and got the below error..
> 
> ![image](https://private-user-images.githubusercontent.com/64365715/316612150-372918bc-f094-41ec-a5e2-f804ca07d2f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzOTI2MzQsIm5iZiI6MTcxMTM5MjMzNCwicGF0aCI6Ii82NDM2NTcxNS8zMTY2MTIxNTAtMzcyOTE4YmMtZjA5NC00MWVjLWE1ZTItZjgwNGNhMDdkMmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE4NDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMWMwNWY4YzFhYmJmNGE5ZWU4MjQ1M2Q4YWM0MTcxMjdiMmFlYmVkMTE3ZWI3ZmIzMTc3NTAzZjU3ODg2NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b_LSRI2oG7koH4KaC5_OgbGB7fDHkQcgvoFggmcKYjo)

this error is likely unrelated btw.

**Comment by Dreamlinerm** [comment]
@jakche can i get your login information again?

**Comment by Dreamlinerm** [comment]
fixed in 623e2bbf69aae885b8c176f4a6936eeaa90f185f

**Comment by Dreamlinerm** [comment]
@alok1nanda will release new version today

**Comment by Dreamlinerm** [comment]
@alok1nanda sry could not fix faster since I only today managed to login to hotstar with vpn
