### ISSUE TITLE
Hulu

### ISSUE THREAD

**Issue by smsilva98** [Dreamlinerm/Netflix-Prime-Auto-Skip#95]
Are there any current plans to add the other major streaming providers?

**Comment by Dreamlinerm** [comment]
@smsilva98 I will add HBO next. Somebody already gave me their account credentials for that. Hulu I don't have an account for, but probably that next and then JOYN.  YouTube I will probably never add since there are so many great alternatives already there. For further questions you can also come to the discord server https://discord.gg/5fBYathA7d .

**Comment by Dreamlinerm** [comment]
I did not program it yet because I am busy and had other things to do. before that i upgraded the popup design and fixed some issues

**Comment by Dreamlinerm** [comment]
I am also unsure if there is a way to make these permissions optional without everyone having their browser experience disrupted by the permission popup, because like 200 people will uninstall every time they see a popup.

**Comment by smsilva98** [comment]
Thank you, I'm going to look through the code and see if I can add support for Hulu. I'll join the discord either tonight or tomorrow.

**Comment by Dreamlinerm** [comment]
At hulu:
With the browser extension SingleFile you can also make snapshots of the website Hulu and I can try to program with them, but to test it out you will have to do it or I need an account.
Here are the conditions where I would need a snapshot:
Home Page
Video where skip intro button is showing
Video where skip outro/ go to next episode button is showing
snapshot where there is an ad if there are ads
snapshot with subtitles if they need improving

**Comment by Dreamlinerm** [comment]
@smsilva98 added HBO in #97

**Comment by Dreamlinerm** [comment]
I think i wont program hulu since its about to merge with disney plus and everything will eventually be on disney

**Comment by Dreamlinerm** [comment]
.
