### ISSUE TITLE
Prime movies ad not skipped

### ISSUE THREAD

**Issue by plsspamme** [Dreamlinerm/Netflix-Prime-Auto-Skip#96]
### Describe the bug
Prime movies ad not skipped.

### To Reproduce
Selected "The Flash" movie and start playing.
And these movies too:
Transformers: Rise of the Beasts
https://www.amazon.com/gp/video/detail/B0BX24RV7D/ref=atv_mv_hom_c_LvG2mH_2_2?jic=44%7CCgtmcmVld2l0aGFkcxIMc3Vic2NyaXB0aW9uEgRzdm9k

### Expected behavior
Either the Ad plays really quickly or the Ad doesn't show.

### Background information:
 - Exact URL(includes show): [e.g. amazon.de, amazon.com, netflix.ca]
https://www.amazon.com/gp/video/detail/B0C9GSL22W/ref=atv_mv_hom_c_5crrHZ_brws_2_6?jic=44%7CCgtmcmVld2l0aGFkcxIMc3Vic2NyaXB0aW9uEgRzdm9k
https://www.amazon.com/gp/video/detail/B0BX24RV7D/ref=atv_mv_hom_c_LvG2mH_2_2?jic=44%7CCgtmcmVld2l0aGFkcxIMc3Vic2NyaXB0aW9uEgRzdm9k
 - Country: USA
 - Browser - chrome
 - Addon-Version - 1.1.2
 - Save the console logs (Press F12) in a txt and upload them here with ctrl+v or dragging
[TheFlash.txt](https://github.com/Dreamlinerm/Netflix-Prime-Auto-Skip/files/14942698/TheFlash.txt)
[Transformers.txt](https://github.com/Dreamlinerm/Netflix-Prime-Auto-Skip/files/14942699/Transformers.txt)

**Comment by Dreamlinerm** [comment]
I will have to use VPN to go on amazon.com later and try to fix this, from the console.logs there is no apparent issue

**Comment by Dreamlinerm** [comment]
I went on the show and the ad is skipped no problem. There is a content.js script run in the console.log. Can you maybe try to only run my extension with all other extensions disabled and see if the problem still persists? 

You can do that easily by allowing my extension to run in a private window and open one for example:
Or disable all others temporarily.

**Comment by plsspamme** [comment]
You are right. There was a Video Downloader extension that probably caused the issue. I turned that off and no Ads with both movies now plus others.

Thank you very much for checking!

**Comment by Dreamlinerm** [comment]
Good that you uploaded the console logs, many people don't bother. This makes it way easier and faster.
