### ISSUE TITLE
What's wrong with Netflix?

### ISSUE THREAD

**Issue by smsilva98** [Dreamlinerm/Netflix-Prime-Auto-Skip#98]
Netflix is the most used streaming service, so it is the most important streaming service for getting working. What is currently preventing adblocking from working on Netflix, and what are steps we can take to fix it?

**Comment by Dreamlinerm** [comment]
I am not actively using netflix with ads, therefore i do not notice if netflix changes anything related to adblock. you are the first user to report any issue.

**Comment by Dreamlinerm** [comment]
I will look into it today and publish a new version

**Comment by Dreamlinerm** [comment]
I did not change anything related to Netflix in my last update, so if something is not working, it is because of Netflix changing their website. I am only one person doing this as a hobby, so if there is any problem, an issue has to be opened for it to get fixed since I won't notice in time.

**Comment by Dreamlinerm** [comment]
And since I don't have a Netflix ad account, I have to pay 5 every time there is some problem

**Comment by Dreamlinerm** [comment]
I checked right now on my device the ads are skipped fine, I don't know what the problem is without further information.

**Comment by smsilva98** [comment]
That was my mistake. I was looking at the Android compatibility table and thought it referred to browser compatibility on desktops. I will submit a PR to add a table under "Install in browser" similar to the one under "Install on Android" to clarify it so someone else doesn't have the same misunderstanding.
